name: 'Testing config import theme'
type: theme
base theme: stable9
description: 'Theme for testing profile uninstall'
# version: VERSION
regions:
  sidebar_first: 'Left sidebar'
  sidebar_second: 'Right sidebar'
  content: Content
  header: Header
  footer: Footer
  highlighted: Highlighted
  help: Help

# Information added by Drupal.org packaging script on 2026-02-05
version: '10.6.3'
project: 'drupal'
datestamp: 1770280411
