name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2025-12-09
version: '10.5.8'
project: 'drupal'
datestamp: 1765309401
