name: 'Configuration Manager'
type: module
description: 'Allows importing and exporting configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2025-11-06
version: '10.5.5'
project: 'drupal'
datestamp: 1762403446
